name: Update Status

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Clone Repo
        uses: actions/checkout@master
        with:
          repository: ${{ secrets.REPO_NAME }}
      - name: Install dependencies.
        run: |
          pip install pyrogram tgcrypto pytz
          pip install --upgrade pip
      - name: Run the UserClient.
        run: |
          python3 botstatus_teletips.py
        env:
          APP_ID: ${{ secrets.APP_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          